import { useWallet } from '@solana/wallet-adapter-react';
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { WalletMultiButton } from '@ui/wallet-adapter';
import { WalletConnectedButton } from '@components/wallet';
import { isSolanaWallet } from '@core/wallet';

const Home: NextPage = () => {
  const { connected, wallet } = useWallet();
  const walletAdapter = wallet?.adapter();
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">{walletAdapter?.publicKey?.toBase58() ?? 'Wallet not connected.'}</h1>
        {connected && walletAdapter && isSolanaWallet(walletAdapter) ? (
          <WalletConnectedButton wallet={walletAdapter} />
        ) : (
          <WalletMultiButton />
        )}
      </main>
    </div>
  );
};

export default Home;
